import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import styles from './page.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.main}>
          <div className={styles.description}>
            <div className={styles.grid}>
              <a href="/">
                <Image
                  src="/MeatBerries-Name.png"
                  alt="MeatBerries-Name"
                  className={styles.logo}
                  width={300 }
                  height={139}
                  priority
                />
              </a>
            </div>
              <a
                href="/Band"
                className={styles.card}
              >
              <h2 className=" ">
                Band
              </h2>
            </a>
          </div>
          {children}
        </main>
      </body>
    </html>
  )
}
